repos:
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.11.1'
    hooks:
    - id: mypy
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.1
  hooks:
    - id: ruff
    - id: ruff-format
