[tool.poetry]
name = "fsspec-browser"
version = "0.1.0"
description = "**fsspec-browser** utilizes the fsspec python library to implement a minimal frontend to browse stored data."
authors = ["Jens Blawatt <jblawatt@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.112.0"
fsspec = "^2024.6.1"
jinja2 = "^3.1.4"
pydantic-settings = "^2.4.0"
uvicorn = "^0.30.5"
s3fs = "^2024.6.1"
adlfs = "^2024.7.0"

[tool.poetry.group.dev.dependencies]
isort = "^5.13.2"
ruff = "^0.5.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
