name: Build and Push Docker Image

on:
  push:
    branches:
      - feat/gh-actions
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          platforms: ${{ matrix.platforms }}
          file: docker/Dockerfile
          tags: jblawatt/fsspec-browser:latest,jblawatt/fsspec-browser:v0.1
