name: Build and Push Docker Image

on:
  push:
    branches:
      - feat/gh-actions
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v2
        with:
          images: |
            ghcr.io/${{ github.repository }} 

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: docker/Dockerfile
          tags: jblawatt/fsspec-browser:latest,jblawatt/fsspec-browser:v0.1
